# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lYNyixJPdjXDhijryn3T3B1UQU3ZOH-B
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

st.set_page_config(
    page_title="Dashboard Klasterisasi Transaksi Digital Indonesia",
    page_icon="🗺️",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

    .main { background-color: #0f1117; }

    .metric-card {
        background: linear-gradient(135deg, #1e2130 0%, #252a3a 100%);
        border: 1px solid #2d3550;
        border-radius: 12px;
        padding: 20px 24px;
        text-align: center;
    }
    .metric-label {
        font-size: 11px;
        font-weight: 600;
        letter-spacing: 0.08em;
        text-transform: uppercase;
        color: #8892a4;
        margin-bottom: 6px;
    }
    .metric-value {
        font-size: 32px;
        font-weight: 700;
        color: #e8eaf0;
        line-height: 1;
    }
    .metric-sub {
        font-size: 12px;
        color: #8892a4;
        margin-top: 4px;
    }
    .cluster-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
    }
    .section-title {
        font-size: 13px;
        font-weight: 600;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        color: #8892a4;
        margin-bottom: 16px;
        padding-bottom: 8px;
        border-bottom: 1px solid #2d3550;
    }
    div[data-testid="stSidebar"] {
        background-color: #161822;
        border-right: 1px solid #2d3550;
    }
    div[data-testid="stSidebar"] .stSelectbox label,
    div[data-testid="stSidebar"] .stSlider label {
        color: #8892a4 !important;
        font-size: 12px !important;
        font-weight: 600 !important;
        text-transform: uppercase !important;
        letter-spacing: 0.06em !important;
    }
</style>
""", unsafe_allow_html=True)

CLUSTER_COLORS = {
    'Digital Rendah':              '#e41a1c',
    'Digital Menengah':            '#377eb8',
    'Digital Maju':                '#4daf4a',
    'Digital Spesialis Non-Tunai': '#984ea3',
}
CLUSTER_ORDER = ['Digital Rendah', 'Digital Menengah', 'Digital Maju', 'Digital Spesialis Non-Tunai']

@st.cache_data
def load_data():
    df = pd.read_csv('hasil_clustering_final.csv')
    df['Tahun'] = df['Tahun'].astype(int)
    return df

df = load_data()
years = sorted(df['Tahun'].unique())

with st.sidebar:
    st.markdown("### 🗺️ Dashboard Filter")
    st.markdown("---")

    selected_year = st.selectbox(
        "Tahun",
        options=years,
        index=len(years) - 1
    )

    st.markdown("---")
    selected_clusters = st.multiselect(
        "Tampilkan Cluster",
        options=CLUSTER_ORDER,
        default=CLUSTER_ORDER
    )

    st.markdown("---")
    st.markdown("""
    <div style='font-size:11px; color:#8892a4; line-height:1.7'>
    <b style='color:#c5c9d6'>Tentang Dashboard</b><br>
    Klasterisasi K-Means pada 34 provinsi Indonesia berdasarkan pola transaksi keuangan digital 2021–2025.<br><br>
    <b style='color:#c5c9d6'>Variabel:</b><br>
    • Outflow Tunai<br>
    • Kartu ATM/Debet<br>
    • Server-Based<br>
    • SKNBI Asal
    </div>
    """, unsafe_allow_html=True)

df_year = df[df['Tahun'] == selected_year].copy()
df_filtered = df_year[df_year['Target_Semantic'].isin(selected_clusters)]

st.markdown(f"""
<div style='margin-bottom: 28px;'>
    <div style='font-size:11px; font-weight:600; letter-spacing:0.1em; text-transform:uppercase; color:#6c7a94; margin-bottom:6px;'>
        SKRIPSI · K-MEANS CLUSTERING
    </div>
    <h1 style='font-size:24px; font-weight:700; color:#e8eaf0; margin:0; line-height:1.3;'>
        Klasterisasi Transaksi Digital Indonesia
    </h1>
    <p style='font-size:14px; color:#8892a4; margin-top:6px;'>
        Analisis temporal 34 provinsi · 2021–2025 · {selected_year} ditampilkan
    </p>
</div>
""", unsafe_allow_html=True)

counts = df_year['Target_Semantic'].value_counts()
cols = st.columns(4)
card_data = [
    ("Digital Maju",                "🟢", CLUSTER_COLORS['Digital Maju']),
    ("Digital Menengah",            "🔵", CLUSTER_COLORS['Digital Menengah']),
    ("Digital Rendah",              "🔴", CLUSTER_COLORS['Digital Rendah']),
    ("Digital Spesialis Non-Tunai", "🟣", CLUSTER_COLORS['Digital Spesialis Non-Tunai']),
]
for col, (label, icon, color) in zip(cols, card_data):
    n = counts.get(label, 0)
    pct = n / len(df_year) * 100
    with col:
        st.markdown(f"""
        <div class="metric-card" style="border-top: 3px solid {color};">
            <div class="metric-label">{label}</div>
            <div class="metric-value">{n}</div>
            <div class="metric-sub">{pct:.0f}% dari 34 provinsi</div>
        </div>
        """, unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

col1, col2 = st.columns([1, 1])

with col1:
    st.markdown('<div class="section-title">Distribusi Cluster per Tahun</div>', unsafe_allow_html=True)

    dist_data = df[df['Target_Semantic'].isin(selected_clusters)].groupby(
        ['Tahun', 'Target_Semantic']
    ).size().reset_index(name='Jumlah')

    dist_data['Target_Semantic'] = pd.Categorical(
        dist_data['Target_Semantic'], categories=CLUSTER_ORDER, ordered=True
    )
    dist_data = dist_data.sort_values(['Tahun', 'Target_Semantic'])

    fig_bar = px.bar(
        dist_data,
        x='Tahun', y='Jumlah',
        color='Target_Semantic',
        color_discrete_map=CLUSTER_COLORS,
        category_orders={'Target_Semantic': CLUSTER_ORDER},
        barmode='stack',
        text='Jumlah'
    )
    fig_bar.update_traces(textposition='inside', textfont_size=11)
    fig_bar.update_layout(
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font=dict(family='Inter', color='#8892a4', size=12),
        legend=dict(
            title='', orientation='h',
            yanchor='bottom', y=1.02, xanchor='left', x=0,
            font=dict(size=11)
        ),
        xaxis=dict(
            title='Tahun', tickmode='array',
            tickvals=years, gridcolor='#2d3550', tickcolor='#2d3550'
        ),
        yaxis=dict(title='Jumlah Provinsi', gridcolor='#2d3550'),
        margin=dict(l=0, r=0, t=40, b=0),
        height=320
    )
    st.plotly_chart(fig_bar, use_container_width=True)

with col2:
    st.markdown('<div class="section-title">Visualisasi PCA · Separasi Cluster</div>', unsafe_allow_html=True)

    df_pca = df_filtered.copy()
    fig_pca = px.scatter(
        df_pca, x='PCA1', y='PCA2',
        color='Target_Semantic',
        color_discrete_map=CLUSTER_COLORS,
        category_orders={'Target_Semantic': CLUSTER_ORDER},
        hover_data={'Provinsi': True, 'Tahun': True, 'Target_Semantic': True, 'PCA1': ':.2f', 'PCA2': ':.2f'},
        hover_name='Provinsi',
        size_max=12
    )
    fig_pca.update_traces(marker=dict(size=9, opacity=0.8, line=dict(width=0.5, color='white')))
    fig_pca.update_layout(
        paper_bgcolor='rgba(0,0,0,0)',
        plot_bgcolor='rgba(0,0,0,0)',
        font=dict(family='Inter', color='#8892a4', size=12),
        legend=dict(title='', font=dict(size=11)),
        xaxis=dict(title='PC1', gridcolor='#2d3550', zeroline=False),
        yaxis=dict(title='PC2', gridcolor='#2d3550', zeroline=False),
        margin=dict(l=0, r=0, t=10, b=0),
        height=320
    )
    st.plotly_chart(fig_pca, use_container_width=True)

col3, col4 = st.columns([1.1, 0.9])

with col3:
    st.markdown(f'<div class="section-title">Daftar Provinsi · {selected_year}</div>', unsafe_allow_html=True)

    display_cols = ['Provinsi', 'Target_Semantic', 'outflow_tunai', 'kartu_atm_debet', 'Server_Based', 'SKNBI_Asal']
    df_table = df_filtered[display_cols].copy()
    df_table.columns = ['Provinsi', 'Cluster', 'Outflow Tunai', 'ATM/Debet', 'Server-Based', 'SKNBI Asal']
    df_table = df_table.sort_values('Cluster')
    df_table[['Outflow Tunai', 'ATM/Debet', 'Server-Based', 'SKNBI Asal']] = \
        df_table[['Outflow Tunai', 'ATM/Debet', 'Server-Based', 'SKNBI Asal']].round(3)

    st.dataframe(
        df_table,
        use_container_width=True,
        height=320,
        hide_index=True,
        column_config={
            "Cluster": st.column_config.TextColumn("Cluster", width="medium"),
            "Provinsi": st.column_config.TextColumn("Provinsi", width="medium"),
        }
    )

with col4:
    st.markdown(f'<div class="section-title">Profil Rata-rata Fitur · {selected_year}</div>', unsafe_allow_html=True)

    features = ['outflow_tunai', 'kartu_atm_debet', 'Server_Based', 'SKNBI_Asal']
    feat_labels = ['Outflow Tunai', 'ATM/Debet', 'Server-Based', 'SKNBI Asal']

    fig_radar = go.Figure()
    for cluster in CLUSTER_ORDER:
        if cluster not in selected_clusters:
            continue
        sub = df_year[df_year['Target_Semantic'] == cluster]
        if sub.empty:
            continue
        vals = sub[features].mean().tolist()
        vals_norm = [(v - df_year[features[i]].min()) /
                     (df_year[features[i]].max() - df_year[features[i]].min() + 1e-9)
                     for i, v in enumerate(vals)]
        vals_norm += [vals_norm[0]]

        fig_radar.add_trace(go.Scatterpolar(
            r=vals_norm,
            theta=feat_labels + [feat_labels[0]],
            fill='toself',
            name=cluster,
            line_color=CLUSTER_COLORS[cluster],
            fillcolor=CLUSTER_COLORS[cluster],
            opacity=0.25
        ))

    fig_radar.update_layout(
        polar=dict(
            bgcolor='rgba(0,0,0,0)',
            radialaxis=dict(visible=True, range=[0, 1], gridcolor='#2d3550', tickcolor='#2d3550', color='#8892a4'),
            angularaxis=dict(gridcolor='#2d3550', color='#8892a4')
        ),
        paper_bgcolor='rgba(0,0,0,0)',
        font=dict(family='Inter', color='#8892a4', size=12),
        legend=dict(title='', font=dict(size=11), orientation='h', yanchor='bottom', y=-0.15),
        margin=dict(l=20, r=20, t=20, b=20),
        height=320
    )
    st.plotly_chart(fig_radar, use_container_width=True)

st.markdown('<div class="section-title">Perubahan Cluster Antar Tahun (Semua Periode)</div>', unsafe_allow_html=True)

pivot = df.pivot_table(index='Provinsi', columns='Tahun', values='Target_Semantic', aggfunc='first')
change_records = []
for i in range(len(years) - 1):
    y1, y2 = years[i], years[i+1]
    changed = pivot[pivot[y1] != pivot[y2]]
    for prov, row in changed.iterrows():
        change_records.append({
            'Provinsi': prov,
            'Periode': f'{y1} → {y2}',
            'Cluster Awal': row[y1],
            'Cluster Akhir': row[y2],
            'Arah': '⬆️ Naik' if CLUSTER_ORDER.index(row[y2]) > CLUSTER_ORDER.index(row[y1]) else '⬇️ Turun'
        })

if change_records:
    df_changes = pd.DataFrame(change_records)
    st.dataframe(df_changes, use_container_width=True, hide_index=True, height=200)
else:
    st.info("Tidak ada perubahan cluster antar tahun.")

st.markdown('<div class="section-title">Peta Cluster Provinsi × Tahun</div>', unsafe_allow_html=True)

pivot_display = pivot.reset_index()
pivot_display.columns.name = None
st.dataframe(pivot_display, use_container_width=True, hide_index=True, height=300)

st.markdown("""
<div style='text-align:center; color:#4a5568; font-size:11px; margin-top:40px; padding-top:20px; border-top:1px solid #2d3550;'>
    Klasterisasi Provinsi Indonesia · K-Means · 2021–2025 · Skripsi
</div>
""", unsafe_allow_html=True)